my first job:
  stage: build
  image: node
  script: 
    - npm install express
    - node server.js  &
    - sleep 5
    - echo "Webapp started..."
    - curl http://localhost:3000/data | grep -i welcome


